#ifndef I2C_HEADER_H
#define I2C_HEADER_H

#include "I2C_Private.h"
#include "I2C_Config.h"
#include "../../LIB/STD_TYPES.h"
#include "../../LIB/BIT_MATH.h"
#include "../../MCAL/DIO/DIO_Header.h"
#include "../../MCAL/EXTI/EXTI_Header.h"


typedef enum{
    I2C_OK,
    I2C_ERROR_MASTER_StartCondition_ACK,
    I2C_ERROR_MASTER_RestartCondition_ACK,
    I2C_ERROR_MASTER_WRITE_TO_SLAVE_ACK,
    I2C_ERROR_MASTER_WRITE_TO_SLAVE_NACK,
    I2C_ERROR_MASTER_READ_FROM_SLAVE_ACK,
    I2C_ERROR_MASTER_READ_FROM_SLAVE_NACK,
    I2C_ERROR_MASTER_SEND_TO_SLAVE_ACK,
    I2C_ERROR_MASTER_SEND_TO_SLAVE_NACK,
    I2C_ERROR_MASTER_RECIEVE_FROM_SLAVE_ACK,
    I2C_ERROR_MASTER_RECIEVE_FROM_SLAVE_NACK,

    I2C_ERROR_SLAVE_RECIEVE_ADDRESS_READ_ACK,
    I2C_ERROR_SLAVE_RECIEVE_FROM_MASTER_ACK,
    I2C_ERROR_SLAVE_RECIEVE_ADDRESS_WRITE_ACK,
    I2C_ERROR_SLAVE_TRANSMIT_TO_MASTER_ACK,   
}I2C_ERROR_TABLE;

void I2C_Master_Init(u8 Master_Address);
void I2C_SLAVE_Init(u8 SLAVE_ADDRESS);

//MASTER CONTROL FUNCS
I2C_ERROR_TABLE I2C_MASTER_StartCondition();
I2C_ERROR_TABLE I2C_MASTER_RestartCondition();
void I2C_MASTER_StopCondition();

//MASTER TRANSMIT AND RECIEVE FUNCS WITH ACKNOWLEDGE
I2C_ERROR_TABLE I2C_MASTER_WRITE_ACK(u8 Slave_Address);
I2C_ERROR_TABLE I2C_MASTER_SEND_DATA_ACK(u8 Data);
I2C_ERROR_TABLE  I2C_MASTER_READ_ACK(u8 SLAVE_ADDRESS);
I2C_ERROR_TABLE I2C_MASTER_RECIEVE_ACK(u8 *DATA);


//SLAVE TRANSMIT AND RECIEVE FUNCS WITH ACKNOWLEDGE
I2C_ERROR_TABLE I2C_SLAVE_WRITE_RECIEVE_ACK();
I2C_ERROR_TABLE I2C_SLAVE_RECIEVE_ACK(u8 *Data);
I2C_ERROR_TABLE I2C_SLAVE_READ_RECIEVE_ACK();
I2C_ERROR_TABLE I2C_SLAVE_TRANSMIT_ACK(u8 DATA);


#endif