#include "I2C_Header.h"

//MASTER and SLAVE Init

void I2C_Master_Init(u8 Master_Address){
    set_bit(TWCR_CONTROL_REG,TWCR_ENABLE_ACK_BIT); //ENABLE ACKNOWLEDGE

    *TWBR_BIT_RATE_REG =2;     //400khz


    switch (PRESCALAR)
    {
    case PRESCALAR_1:
        clear_bit(TWSR_STATUS_REG,TWSR_PRESCALAR_1_BIT);
        clear_bit(TWSR_STATUS_REG,TWSR_PRESCALAR_2_BIT);
        break;
    case PRESCALAR_4:
        set_bit(TWSR_STATUS_REG,TWSR_PRESCALAR_1_BIT);
        clear_bit(TWSR_STATUS_REG,TWSR_PRESCALAR_2_BIT);
        break;
    case PRESCALAR_16:
        clear_bit(TWSR_STATUS_REG,TWSR_PRESCALAR_1_BIT);
        set_bit(TWSR_STATUS_REG,TWSR_PRESCALAR_2_BIT);    
        break;
    case PRESCALAR_64:
        set_bit(TWSR_STATUS_REG,TWSR_PRESCALAR_1_BIT);
        set_bit(TWSR_STATUS_REG,TWSR_PRESCALAR_2_BIT);
        break;                    
    default:
        break;
    }

    //SET TO 0 WHEN NO NEED TO THE MASTER TO BE ADDRESSED
    if (Master_Address != 0x00){
        *TWAR_SLAVE_ADDRESS_REG  = (Master_Address>>1);   //SET MASTER ADDRESS
    }
    
    set_bit(TWCR_CONTROL_REG,TWCR_ENABLE_BIT);  //ENABLE I2C
}


void I2C_SLAVE_Init(u8 SLAVE_ADDRESS){
    set_bit(TWCR_CONTROL_REG,TWCR_ENABLE_ACK_BIT); //ENABLE ACKNOWLEDGE

    *TWAR_SLAVE_ADDRESS_REG  = (SLAVE_ADDRESS>>1); //SET SLAVE ADDRESS

    set_bit(TWCR_CONTROL_REG,TWCR_ENABLE_BIT);    //ENABLE I2C

}


// MASTER START AND STOP FUNCTIONS

I2C_ERROR_TABLE I2C_MASTER_StartCondition(){
    I2C_ERROR_TABLE error = I2C_OK;   //SA5AN EL ERROR TYPE
    set_bit(TWCR_CONTROL_REG,TWCR_START_BIT);
    set_bit(TWCR_CONTROL_REG,TWCR_INT_FLAG_BIT);
    while (get_bit(TWCR_CONTROL_REG,TWCR_INT_FLAG_BIT)); //FE HAD TANY SHA5AL
    if(*TWSR_STATUS_REG & STATUS_BITS_MASK != I2C_MASTER_START_TRANSMITION){
        error = I2C_ERROR_MASTER_StartCondition_ACK;
    }
    return error; 
}


I2C_ERROR_TABLE I2C_MASTER_RestartCondition(){
    I2C_ERROR_TABLE error = I2C_OK;
    set_bit(TWCR_CONTROL_REG,TWCR_START_BIT);
    set_bit(TWCR_CONTROL_REG,TWCR_INT_FLAG_BIT);
    while (get_bit(TWCR_CONTROL_REG,TWCR_INT_FLAG_BIT));
    if(*TWSR_STATUS_REG & STATUS_BITS_MASK != I2C_MASTER_REPEATED_START_TRANSMITION){
        error = I2C_ERROR_MASTER_RestartCondition_ACK;
    }
    return error;
}

void I2C_MASTER_StopCondition(){
    set_bit(TWCR_CONTROL_REG,TWCR_STOP_BIT);
    set_bit(TWCR_CONTROL_REG,TWCR_INT_FLAG_BIT);    
}

// MASTER WRITE AND SEND WITH ACKWONLEDGE

I2C_ERROR_TABLE I2C_MASTER_WRITE_ACK(u8 Slave_Address){
    I2C_ERROR_TABLE error = I2C_OK;
    *TWDR_DATA_REG = (Slave_Address>>1);
    clear_bit(TWDR_DATA_REG,TWDR_DATA_0_BIT);
    clear_bit(TWCR_CONTROL_REG,TWCR_START_BIT);
    set_bit(TWCR_CONTROL_REG,TWCR_INT_FLAG_BIT);
    while (get_bit(TWCR_CONTROL_REG,TWCR_INT_FLAG_BIT)==0);
    if(*TWSR_STATUS_REG & STATUS_BITS_MASK != I2C_SLAVE_ADDRESS_WRITE_ACK){
        error = I2C_ERROR_MASTER_WRITE_TO_SLAVE_ACK;  
    }
    return error;
}


I2C_ERROR_TABLE I2C_MASTER_SEND_DATA_ACK(u8 Data){
    I2C_ERROR_TABLE error = I2C_OK;
    *TWDR_DATA_REG = Data;
    set_bit(TWCR_CONTROL_REG,TWCR_INT_FLAG_BIT);
    while (get_bit(TWCR_CONTROL_REG,TWCR_INT_FLAG_BIT)==0);
    if(*TWSR_STATUS_REG & STATUS_BITS_MASK != I2C_MASTER_DATA_TRANSMITTED_ACK){
        error = I2C_ERROR_MASTER_SEND_TO_SLAVE_ACK;  
    }
    return error;
}

// MASTER READ AND RECIEVE WITH ACKNOWLEDGE

I2C_ERROR_TABLE  I2C_MASTER_READ_ACK(u8 SLAVE_ADDRESS){
    I2C_ERROR_TABLE error = I2C_OK;
    *TWDR_DATA_REG =  (SLAVE_ADDRESS>>1);
    set_bit(TWDR_DATA_REG,TWDR_DATA_0_BIT); //THE CONDITION TO READ
    clear_bit(TWCR_CONTROL_REG,TWCR_START_BIT);
    set_bit(TWCR_CONTROL_REG,TWCR_INT_FLAG_BIT);
    while (get_bit(TWCR_CONTROL_REG,TWCR_INT_FLAG_BIT)==0);
    if (*TWSR_STATUS_REG & STATUS_BITS_MASK != I2C_SLAVE_ADDRESS_READ_ACK)
    {
        error = I2C_ERROR_MASTER_READ_FROM_SLAVE_ACK;
    }
    return error;
    
}

I2C_ERROR_TABLE I2C_MASTER_RECIEVE_ACK(u8 *DATA){
    I2C_ERROR_TABLE error = I2C_OK;
    set_bit(TWCR_CONTROL_REG,TWCR_INT_FLAG_BIT);
    while (get_bit(TWCR_CONTROL_REG,TWCR_INT_FLAG_BIT)==0);
    if (*TWSR_STATUS_REG & STATUS_BITS_MASK != I2C_MASTER_DATA_RECEIVED_ACK){
        error = I2C_ERROR_MASTER_RECIEVE_FROM_SLAVE_ACK;
    }
    *DATA = *TWDR_DATA_REG;
    return error;
}

/*============================================================SLAVE FUNCS=============================================================*/


//Slave READ & RECIEVE FUNCTIONS
I2C_ERROR_TABLE I2C_SLAVE_WRITE_RECIEVE_ACK(){
    I2C_ERROR_TABLE error = I2C_OK;
    set_bit(TWCR_CONTROL_REG,TWCR_INT_FLAG_BIT);
    while(  get_bit(TWCR_CONTROL_REG,TWCR_INT_FLAG_BIT)==0 ); 
    if (*TWSR_STATUS_REG & STATUS_BITS_MASK != I2C_SLAVE_RECIEVE_ADDRESS_READ_ACK)
    {
        error = I2C_ERROR_SLAVE_RECIEVE_ADDRESS_READ_ACK;
    }
    return error;
}

I2C_ERROR_TABLE I2C_SLAVE_RECIEVE_ACK(u8 *Data){
    I2C_ERROR_TABLE error = I2C_OK;
    set_bit(TWCR_CONTROL_REG,TWCR_INT_FLAG_BIT);
    while(  get_bit(TWCR_CONTROL_REG,TWCR_INT_FLAG_BIT)==0); 
    if (*TWSR_STATUS_REG & STATUS_BITS_MASK != I2C_SLAVE_DATA_RECEIVED_ACK )
    {
        error = I2C_ERROR_SLAVE_RECIEVE_FROM_MASTER_ACK;
    }
    *Data=*TWDR_DATA_REG;
    return error;
}


//SLAVE WRITE & TRANSMIT FUNCTIONS

I2C_ERROR_TABLE I2C_SLAVE_READ_RECIEVE_ACK(){
    I2C_ERROR_TABLE error = I2C_OK;
    set_bit(TWCR_CONTROL_REG,TWCR_INT_FLAG_BIT);
    while( get_bit(TWCR_CONTROL_REG,TWCR_INT_FLAG_BIT)==0 );
    if (*TWSR_STATUS_REG & STATUS_BITS_MASK != I2C_SLAVE_TRANSMIT_ADDRESS_READ_ACK)
    {
        error = I2C_ERROR_SLAVE_RECIEVE_ADDRESS_WRITE_ACK;
    }
    return error;     
}

I2C_ERROR_TABLE I2C_SLAVE_TRANSMIT_ACK(u8 DATA){
    I2C_ERROR_TABLE error= I2C_OK;
    *TWDR_DATA_REG = DATA;
    set_bit(TWCR_CONTROL_REG,TWCR_INT_FLAG_BIT);
    while( get_bit(TWCR_CONTROL_REG,TWCR_INT_FLAG_BIT)==0 );
    if (*TWSR_STATUS_REG & STATUS_BITS_MASK != I2C_SLAVE_DATA_TRANSMITTED_ACK)
    {
        error = I2C_ERROR_SLAVE_TRANSMIT_TO_MASTER_ACK;
    }
    return error;    
}


